name: json_rest_server
description: Json Rest Server is a RESTful server based on JSON
version: 1.0.0
homepage: https://github.com/rodrigorahman/json_rest_server

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.1
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  json_rest_server: json_rest_server

